/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// Register addresses for STM32F407

/* RCC */
#define RCC_APB1ENR   (*((volatile uint32_t*)0x40023840))

/* GPIOA */
#define GPIOA_MODER   (*((volatile uint32_t*)0x40020000))
#define GPIOA_AFRL    (*((volatile uint32_t*)0x40020020))

/* USART2 */
#define USART2_SR     (*((volatile uint32_t*)0x40004400))
#define USART2_DR     (*((volatile uint32_t*)0x40004404))
#define USART2_BRR    (*((volatile uint32_t*)0x40004408))
#define USART2_CR1    (*((volatile uint32_t*)0x4000440C))



#define RCC_AHB1ENR   (*((volatile uint32_t*)0x40023830))
#define GPIOD_MODER   (*((volatile uint32_t*)0x40020C00))
#define GPIOD_ODR     (*((volatile uint32_t*)0x40020C14))


void UART_SendChar(char ch);
void UART_SendString(char *str);

void delay(volatile uint32_t count) {
    while(count--);
}



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	 delay(1000000);

	 /* GPIOA Clock Enable */
	 RCC_AHB1ENR |= (1<<0);

	 /* USART2 Clock Enable */
	 RCC_APB1ENR |= (1<<17);

    // Enable GPIOD clock
    RCC_AHB1ENR |= (1 << 3);

    delay(100);

    /* Clear PA2 Mode */
    GPIOA_MODER &= ~(3<<4);

    /* Set PA2 Alternate Function */
    GPIOA_MODER |= (2<<4);

    GPIOA_MODER &= ~(3<<6);
    GPIOA_MODER |= (2<<6);

    GPIOA_AFRL &= ~(0xF << 8);
    GPIOA_AFRL |=  (7 << 8);

    GPIOA_AFRL &= ~(0xF << 12);
    GPIOA_AFRL |=  (7 << 12);

    USART2_BRR = 0x0683;


    USART2_CR1 |= (1 << 13);   // UE
    USART2_CR1 |= (1 << 3);    // TE
    USART2_CR1 |= (1 << 2);    // RE


    UART_SendChar('A');

    // Set PD12, PD13, PD14, PD15 as output (MODER = 01)
    GPIOD_MODER |= (1 << 24);  // PD12
    GPIOD_MODER |= (1 << 26);  // PD13
    GPIOD_MODER |= (1 << 28);  // PD14
    GPIOD_MODER |= (1 << 30);  // PD15



    /* Loop forever */
	//while(1)
	{
	    // Turn ON all 4 LEDs
	            GPIOD_ODR |= (1 << 12) | (1 << 13) | (1 << 14) | (1 << 15);
	            delay(500000);

	            // Turn OFF all 4 LEDs
	            GPIOD_ODR &= ~((1 << 12) | (1 << 13) | (1 << 14) | (1 << 15));
	            delay(500000);
	}
}


void UART_SendChar(char ch)
{
    while (!(USART2_SR & (1 << 7)));   // Wait until TXE = 1

    USART2_DR = ch;
}

void UART_SendString(char *str)
{
    while(*str)
    {
        UART_SendChar(*str);
        str++;
    }
}
